#[macro_use]
extern crate clap;
extern crate regex;
extern crate xml;

pub mod parse;
pub mod serialize;

use clap::{App, Arg};
use std::fs::File;
use std::io::{BufReader, Read};

fn main() {
    let args = App::new("script-extractor")
                   .version(&crate_version!())
                   .about("Parse movie scripts into a structured format")
                   .after_help("Input has to be in the format generated by \
                                poppler's 'pdftohtml -xml'.\n\
                                Reads from stdin if no file or '-' is specified.")
                   .arg(Arg::with_name("input-file")
                            .help("input file in poppler's xml format")
                            .index(1)
                            .validator(check_file_exists))
                   .get_matches();

    let mut input: Box<Read> = if let Some(input_file) = args.value_of("input-file") {
        if input_file == "-" {
            Box::new(BufReader::new(std::io::stdin()))
        } else {
            let file_reader = File::open(input_file).expect("Cannot open input-file");
            Box::new(BufReader::new(file_reader))
        }
    } else {
        Box::new(BufReader::new(std::io::stdin()))
    };

    let scenes = parse::parse_script(&mut input);

    serialize::xml::format_script(&scenes, &mut std::io::stdout()).unwrap();
}

/// Check if the given file exists. Also considers "-" as a valid file.
fn check_file_exists(file_name: String) -> Result<(), String> {
    if file_name == "-" {
        Ok(())
    } else if let Ok(metadata) = std::fs::metadata(&file_name) {
        if metadata.is_file() && !metadata.permissions().readonly() {
            Ok(())
        } else {
            Err(format!("Cannot read file '{}'", file_name))
        }
    } else {
        Err(format!("File '{}' not found", file_name))
    }
}
