#[macro_use]
extern crate clap;

use clap::{App, Arg, ArgGroup};
use std::fs::File;
use std::io::{BufReader, Read};

extern crate script_extractor;
use script_extractor::*;

fn main() {
    let args = App::new("script-extractor")
                   .version(&crate_version!())
                   .about("Parse movie scripts into a structured format")
                   .after_help("Input has to be in the format generated by \
                                poppler's 'pdftohtml -xml'.\n\
                                Reads from stdin if no file or '-' is specified.")
                   .arg(Arg::with_name("input-file")
                            .help("input file in poppler's xml format")
                            .index(1)
                            .validator(check_file_exists))
                   .arg(Arg::with_name("xml")
                            .long("xml")
                            .help("Output script in xml format"))
                   .arg(Arg::with_name("json")
                            .long("json")
                            .help("Output script in json format"))
                   .arg_group(ArgGroup::with_name("output-format")
                                       .add_all(&["xml", "json"])
                                       .required(true))
                   .arg(Arg::with_name("pages")
                            .help("Specify a single page or range of pages to extract")
                            .short("p")
                            .long("pages")
                            .takes_value(true)
                            .validator(|v| if extract_range(&v).is_some() {
                                               Ok(())
                                           } else {
                                               Err(format!("Invalid page range '{}'", v))
                                           }))
                   .get_matches();

    let mut input: Box<Read> = if let Some(input_file) = args.value_of("input-file") {
        if input_file == "-" {
            Box::new(BufReader::new(std::io::stdin()))
        } else {
            let file_reader = File::open(input_file).expect("Cannot open input-file");
            Box::new(BufReader::new(file_reader))
        }
    } else {
        Box::new(BufReader::new(std::io::stdin()))
    };

    let mut script = parse::parse_script(&mut input);

    // filter by pages if requested
    if let Some(range_string) = args.value_of("pages") {
        let range = extract_range(range_string).unwrap_or((0,u32::max_value()));
        script = filter_script(script, range);
    }

    if args.is_present("xml") {
        serialize::xml::format_script(&script, &mut std::io::stdout()).unwrap();
    } else if args.is_present("json") {
        serialize::json::format_script(&script, &mut std::io::stdout()).unwrap();
    }
}

/// Check if the given file exists. Also considers "-" as a valid file.
fn check_file_exists(file_name: String) -> Result<(), String> {
    if file_name == "-" {
        Ok(())
    } else if let Ok(metadata) = std::fs::metadata(&file_name) {
        if metadata.is_file() && !metadata.permissions().readonly() {
            Ok(())
        } else {
            Err(format!("Cannot read file '{}'", file_name))
        }
    } else {
        Err(format!("File '{}' not found", file_name))
    }
}
